version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8800
    volumes:
      - .:/var/www/nti
    ports:
      - "8800:8800"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nti_games
      - POSTGRES_PASSWORD=nti_games_pass
      - POSTGRES_DB=nti_games_test
volumes:
  postgres_data:
