openapi: 3.0.2
info:
  title: 'NTI-Games API'
  version: '1.0.3'
paths:
  /api/auth/login/talent/:
    get:
      operationId: login_talent
      description: 'Авторизация через talent.kruzhok.org'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/logout/talent/:
    get:
      operationId: logout_talent
      description: 'Выход из учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/auth/login/steam/:
    get:
      operationId: login_steam
      description: 'Привязка Steam к учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/logout/steam/:
    get:
      operationId: logout_steam
      description: 'Отвязка Steam от учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/auth/login/blizzard/:
    get:
      operationId: login_blizzard
      description: 'Привязка Blizzard к учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/logout/blizzard/:
    get:
      operationId: logout_blizzard
      description: 'Отвязка Blizzard от учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/analyse/dota/result/:
    get:
      operationId: dota_result
      description: 'Результат анализа для Dota'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DotaResult'
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
  /api/analyse/cs/result/:
    get:
      operationId: cs_result
      description: 'Результат анализа для Cs'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CsResult'
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
  /api/analyse/status/:
    get:
      operationId: task_status
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
  /api/user/:
    get:
      operationId: user
      description: 'Данные авторизованного пользователя'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      security:
      - cookieAuth: []
      tags:
      - user
  /api/user/games/:
    get:
      operationId: user_games
      description: 'Дополнительные данные авторизованного пользователя'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGames'
          description: ''
      security:
      - cookieAuth: []
      tags:
      - user
  /api/analyse/dota/start/:
    post:
      operationId: dota_start
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
  /api/analyse/cs/start/:
    post:
      operationId: cs_start
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
components:
  schemas:
    User:
      type: object
      description: Данные пользователя
      properties:
        id:
          type: integer
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
    UserGames:
      type: object
      description: Дополнительная информация пользователя
      properties:
        pk:
          type: integer
        steam_id:
          type: integer
          nullable: true
        blizzard_id:
          type: integer
          nullable: true
        blizzard_battletag:
          type: string
          nullable: true
        dota_result:
          allOf:
          - $ref: '#/components/schemas/DotaResult'
          - nullable: true
        cs_result:
          allOf:
          - $ref: '#/components/schemas/CsResult'
          - nullable: true
        dota_task:
          type: string
          nullable: true
        cs_task:
          type: string
          nullable: true
    DotaResult:
      description: Work in progress
      type: object
    CsResult:
      description: Work in progress
      type: object
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid