openapi: 3.0.2
info:
  title: 'NTI-Games API'
  version: '1.0.2'
paths:
  /api/auth/login/talent/:
    get:
      operationId: login_talent
      description: 'Авторизация через talent.kruzhok.org'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/logout/talent/:
    get:
      operationId: logout_talent
      description: 'Выход из учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/auth/login/steam/:
    get:
      operationId: login_steam
      description: 'Привязка Steam к учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/logout/steam/:
    get:
      operationId: logout_steam
      description: 'Отвязка Steam от учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/auth/login/blizzard/:
    get:
      operationId: login_blizzard
      description: 'Привязка Blizzard к учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/logout/blizzard/:
    get:
      operationId: logout_blizzard
      description: 'Отвязка Blizzard от учетной записи'
      responses:
        '200':
          description: No response body
      security:
      - cookieAuth: []
      tags:
      - auth
  /api/analyse/dota/result/:
    get:
      operationId: dota_result
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
  /api/analyse/cs/result/:
    get:
      operationId: cs_result
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
  /api/analyse/status/:
    get:
      operationId: task_status
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
  /api/user/:
    get:
      operationId: user
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - user
  /api/user/games/:
    get:
      operationId: user_games
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - user
  /api/analyse/dota/start/:
    post:
      operationId: dota_start
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
  /api/analyse/cs/start/:
    post:
      operationId: cs_start
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      security:
      - cookieAuth: []
      tags:
      - analyse
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid